package com.pearson.Interface.Windows;

import com.pearson.Database.SQL.Column;
import com.pearson.Database.SQL.Database;
import com.pearson.Database.SQL.MySQLTable;
import com.pearson.Interface.Interfaces.XMLInterface;
import com.pearson.Interface.Windows.Models.ItemsSelectedTableModel;
import com.pearson.Utilities.StackTrace;
import noNamespace.Rule;
import noNamespace.RuleType;
import noNamespace.RulesDocument.Rules;
import noNamespace.ShuffleRule;
import org.slf4j.LoggerFactory;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.sql.SQLException;
import java.util.ArrayList;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * @author UMA99J5
 */
public class NewShuffleRuleWindow extends JDialog {
    
    private static org.slf4j.Logger logger = LoggerFactory.getLogger(NewShuffleRuleWindow.class.getName());

    Database database;
    ArrayList<String> tableNames = new ArrayList();
    DefaultListModel<String> listModel;
    boolean firstTimeSelected = true;

    // Variables declaration - do not modify                     
    private javax.swing.JList ColumnsSelectedList;
    private javax.swing.JButton cancelButton;
    private javax.swing.JComboBox columnsComboBox;
    private javax.swing.JButton createShuffleRuleButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel newShuffleRuleLabel;
    private javax.swing.JLabel pseudoCodeLabel;
    private javax.swing.JTextField pseudoCodeTextfield;
    private javax.swing.JLabel selectTableLabel;
    private javax.swing.JLabel shortDescriptionLabel;
    private javax.swing.JPanel shuffleColumnsPane;
    private javax.swing.JTabbedPane shuffleTabbedPane;
    private javax.swing.JCheckBox skipCheckBox;
    private javax.swing.JScrollPane tableScrollPane;
    private javax.swing.JLabel tableSelected;
    private javax.swing.JTable tablesSelectedTable;

    /**
     * Default constructor; creates new form NewShuffleRule
     * <p/>
     * This method throws an exception, but by the time we have allowed the user
     * to enter that window he already should have passed checks on correct
     * connection
     */
    public NewShuffleRuleWindow() throws SQLException {

        database = new Database(com.pearson.Interface.UIManager.getCurrentConnection());

        for (MySQLTable table : database) {
            tableNames.add(table.getTableName());
        }

        listModel = new DefaultListModel();
        initComponents();
        // allow only one table to be selected inside table list
        tablesSelectedTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        setModalityType(ModalityType.APPLICATION_MODAL);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {

        selectTableLabel = new javax.swing.JLabel();
        tableScrollPane = new javax.swing.JScrollPane();
        tablesSelectedTable = new javax.swing.JTable();
        newShuffleRuleLabel = new javax.swing.JLabel();
        tableSelected = new javax.swing.JLabel();
        shortDescriptionLabel = new javax.swing.JLabel();
        shuffleTabbedPane = new javax.swing.JTabbedPane();
        shuffleColumnsPane = new javax.swing.JPanel();
        deleteButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ColumnsSelectedList = new javax.swing.JList();
        pseudoCodeLabel = new javax.swing.JLabel();
        pseudoCodeTextfield = new javax.swing.JTextField();
        cancelButton = new javax.swing.JButton();
        createShuffleRuleButton = new javax.swing.JButton();
        columnsComboBox = new javax.swing.JComboBox();

        setDefaultCloseOperation(DISPOSE_ON_CLOSE);

        selectTableLabel.setText("Select Table");

        tablesSelectedTable.setModel(new ItemsSelectedTableModel(tableNames));
        tablesSelectedTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablesSelectedTableMouseClicked(evt);
            }
        });
        tablesSelectedTable.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                tablesSelectedTableComponentShown(evt);
            }
        });
        tableScrollPane.setViewportView(tablesSelectedTable);

        newShuffleRuleLabel.setText("New Shuffle Rule");
        shortDescriptionLabel.setText("Select Columns");

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        ColumnsSelectedList.setBorder(new javax.swing.border.MatteBorder(null));
        ColumnsSelectedList.setModel(listModel);
        jScrollPane1.setViewportView(ColumnsSelectedList);

        javax.swing.GroupLayout shuffleColumnsPaneLayout = new javax.swing.GroupLayout(shuffleColumnsPane);
        shuffleColumnsPane.setLayout(shuffleColumnsPaneLayout);
        shuffleColumnsPaneLayout.setHorizontalGroup(
                shuffleColumnsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(shuffleColumnsPaneLayout.createSequentialGroup()
                                .addComponent(deleteButton)
                                .addGap(0, 399, Short.MAX_VALUE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        shuffleColumnsPaneLayout.setVerticalGroup(
                shuffleColumnsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(shuffleColumnsPaneLayout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deleteButton)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        shuffleTabbedPane.addTab("List of Columns", shuffleColumnsPane);

        pseudoCodeLabel.setText("Pseudo code");

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        createShuffleRuleButton.setText("Create Shuffle Rule");
        createShuffleRuleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createShuffleRuleButtonActionPerformed(evt);
            }
        });

//helpButton.setText("Help");

        columnsComboBox.setModel(new javax.swing.DefaultComboBoxModel(

        )
        );
        columnsComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                columnsComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(selectTableLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(tableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(497, 497, 497))
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(251, 251, 251)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(tableSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(newShuffleRuleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(254, 254, 254)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(columnsComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(shuffleTabbedPane)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(cancelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                .addGap(60, 60, 60)
                                                                                .addComponent(createShuffleRuleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                .addGap(45, 45, 45)
                                                                        .addComponent(shortDescriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(117, 117, 117))))
        ))));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(newShuffleRuleLabel)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(tableSelected))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(25, 25, 25)
                                                .addComponent(selectTableLabel)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(shortDescriptionLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(columnsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(22, 22, 22)
                                                .addComponent(shuffleTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(cancelButton)
                                        .addComponent(createShuffleRuleButton)
        )));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //private void enableWhereClauseCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enableWhereClauseCheckboxActionPerformed
        // TODO add your handling code here:
        //whereClauseTextArea.setVisible(enableWhereClauseCheckbox.isSelected());
   // }//GEN-LAST:event_enableWhereClauseCheckboxActionPerformed

    //private void errorTextAreaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_errorTextAreaAncestorAdded
        // TODO add your handling code here:
  //  }//GEN-LAST:event_errorTextAreaAncestorAdded

    private void columnsComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_columnsComboBoxActionPerformed

        // mouse clicked on the tables selected triggers this event
        // we want to make sure not to update it
        if (!firstTimeSelected) {
            String column = (String) columnsComboBox.getSelectedItem();
                if(!listModel.contains(column)) listModel.addElement(column);
        }
    }//GEN-LAST:event_columnsComboBoxActionPerformed

    //private void ignoreErrorsCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ignoreErrorsCheckboxActionPerformed
        // TODO add your handling code here:
      //  errorTextArea.setVisible(ignoreErrorsCheckbox.isSelected());
   // }//GEN-LAST:event_ignoreErrorsCheckboxActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // Exit
        dispose();

    }//GEN-LAST:event_cancelButtonActionPerformed

    private void tablesSelectedTableComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tablesSelectedTableComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_tablesSelectedTableComponentShown

    private void tablesSelectedTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablesSelectedTableMouseClicked

        // need to check if a new table was selected for the first time
        // otherwise it triggers actionPerformed on comboBox for some reason
        firstTimeSelected = true;
        columnsComboBox.removeAllItems(); // remove columns from previoulsy selected table
        listModel.removeAllElements();

        int row = tablesSelectedTable.rowAtPoint(evt.getPoint());

        String tableSelected = tableNames.get(row);
        try {
            for (Column column : database.getTable(tableSelected).columns.values()) {
                columnsComboBox.addItem(column.name);
            }
        } catch (SQLException e) {
            logger.debug(e + System.lineSeparator() + StackTrace.getStringFromStackTrace(e));
        }
        firstTimeSelected = false;
    }//GEN-LAST:event_tablesSelectedTableMouseClicked

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        listModel.removeElement(ColumnsSelectedList.getSelectedValue().toString());
    }//GEN-LAST:event_deleteButtonActionPerformed

    // this code works only if we create a rule without being dependent on another rule todo version 1.0 make create new rule dependent on another rule
    private void createShuffleRuleButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_createShuffleRuleButtonActionPerformed

        ArrayList<String> columns = new ArrayList();

        // get all column names user has entered
        for (Object column : listModel.toArray()) {
            columns.add((String) column);
        }

        Rules rulesInSet = XMLInterface.getSetDocument().getMaskingSet().getRules();

        // build the rule according to information from this window
        Rule parentRule = com.pearson.Interface.UIManager.getParentRule();
        Rule newRule;
        // depending on whether is an independent rule or dependent
        if (parentRule == null) {
            newRule = rulesInSet.addNewRule();
            newRule.setId(rulesInSet.getRuleArray().length + "");
        }
        else {
            newRule = parentRule.getDependencies().addNewRule();
            newRule.setId(parentRule.getId().concat("-" + parentRule.getDependencies().getRuleArray().length) + "");
        }
        ShuffleRule newRuleShuffle = newRule.addNewShuffle();
        // add new columns
        for(String column : columns){
            newRuleShuffle.addColumn(column);
        }
        String targetTable = tableNames.get(tablesSelectedTable.getSelectedRow());
        newRule.setTarget(targetTable);
        // get the id of the parent rule and concat it with incremented number of rules inside parent rule dependency
        newRule.setRuleType(RuleType.SHUFFLE);

        com.pearson.Interface.UIManager.update();

        try {
            database.cleanUp();
        } catch (SQLException e) {
            logger.debug("Weren't able to clean up database");
            logger.error(e + System.lineSeparator() + StackTrace.getStringFromStackTrace(e));
        }
        dispose();
    }//GEN-LAST:event_createShuffleRuleButtonActionPerformed
    // End of variables declaration                   
}
